version: '3'

services:
  db:
    build: ./db
    image: mysql:8.0 # Imagen de Docker a utilizar para la base de datos MySQL
    ports:
      - "3310:3306" # Mapeo del puerto 3306 del contenedor al puerto 3306 del host
    environment:
      MYSQL_DATABASE: rumbo_a_la_u # Configuración de la base de datos MySQL
      MYSQL_USER: seba
      MYSQL_PASSWORD: seba
      MYSQL_ROOT_PASSWORD: root
    networks:
      - portafolio-net

  rumbo_a_la_u:
    build: ./rumbo_a_la_u_web
    ports:
      - "8000:8000"
    command: [ "sh", "/app/entrypoint.sh", "db", "3306" ]
    volumes:
      - ./rumbo_a_la_u_web/:/app/rumbo_a_la_u_web
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=rumbo_a_la_u
      - DATABASE_USER=seba
      - DATABASE_PASSWORD=seba
    networks:
      - portafolio-net

networks:
  portafolio-net:
